### ISSUE TITLE
Problem of Build

### ISSUE THREAD

**Issue by heyunwang1** [jhu-saw/sawForceDimensionSDKROS2#1]
Directly use`` vcs import --input https://raw.githubusercontent.com/jhu-saw/sawForceDimensionSDKROS2/main/force_dimension_sdk.repos`` will show
```
HTTP Error 404: Not Found
```

So I download this repos file. when I colcon build it
```
"--- stderr: force_dimension_sdk                                           
CMake Error at CMakeLists.txt:51 (find_package):
  By not providing "FindsawForceDimensionSDK.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "sawForceDimensionSDK", but CMake did not find one.

  Could not find a package configuration file provided by
  "sawForceDimensionSDK" (requested version 2.0.0) with any of the following
  names:

    sawForceDimensionSDKConfig.cmake
    sawforcedimensionsdk-config.cmake

  Add the installation prefix of "sawForceDimensionSDK" to CMAKE_PREFIX_PATH
  or set "sawForceDimensionSDK_DIR" to a directory containing one of the
  above files.  If "sawForceDimensionSDK" provides a separate development
  package or SDK, be sure it has been installed.


---
Failed   <<< force_dimension_sdk [3.03s, exited with code 1]
Aborted  <<< dvrk_robot [3.21s]  "
```

**Comment by adeguet1** [comment]
Sorry about this.  I tested the actual code but installed all the files manually.  I didn't test the vcs installation script and I was using the wrong branch name.  There was also a missing repo in the `.repos` file.  These should be fixed now.  I would recommend you start from the clean ROS2 workspace.  I also added an important note in the README regarding running CMake to locate the SDK from the vendor (ForceDimension).  Can you give it a try to see if the README is clear enough?

**Comment by heyunwang1** [comment]
Thanks！Readme is clear enough, I will try it tomorrow
